//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanly_quanan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiethoadon
    {
        public string ma_cthd { get; set; }
        public string ma_sanpham { get; set; }
        public int soluong { get; set; }
        public string ma_hoadon { get; set; }
    
        public virtual Hoadon Hoadon { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
