//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanly_quanan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoadon()
        {
            this.Chitiethoadons = new HashSet<Chitiethoadon>();
        }
    
        public string ma_hoadon { get; set; }
        public string ngay_dat { get; set; }
        public string ngay_thanhtoan { get; set; }
        public bool tinhtrang { get; set; }
        public string khachhang { get; set; }
        public string sodienthoai_khachhang { get; set; }
        public string ma_taikhoan { get; set; }
        public string ma_ban { get; set; }
    
        public virtual Ban Ban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethoadon> Chitiethoadons { get; set; }
        public virtual Taikhoan Taikhoan { get; set; }
    }
}
