//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanly_quanan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taikhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taikhoan()
        {
            this.Hoadons = new HashSet<Hoadon>();
        }
    
        public string ma_taikhoan { get; set; }
        public string ten_dangnhap { get; set; }
        public string matkhau { get; set; }
        public Nullable<int> ma_quyen { get; set; }
        public string tennhanvien { get; set; }
        public string sodienthoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoadon> Hoadons { get; set; }
        public virtual Quyentruycap Quyentruycap { get; set; }
    }
}
